-- Customer Behavior Analysis

-- Create Database
CREATE database customer_behavior; 
USE customer_behavior;

--  What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG (purchase_amount)
													   FROM customer);

--  Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG (review_rating) DESC
LIMIT 5;
