USE customer_behavior;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG (purchase_amount)
													   FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS "Average Product Rating"
FROM cuStomer
GROUP BY item_purchased
ORDER BY AVG (review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
